### ISSUE TITLE
bitte auf Wohlgeformtheit überprüfen

### ISSUE THREAD

**Issue by csae8092** [KONDE-AT/thun-data#1]
Bitte nur Dateien committen, die auch wohlgeformt sind
Probleme bei `indices/listperson.xml` 

> Bitte nur Dateien committen, die auch wohlgeformt sind
> Probleme bei indices/listperson.xml: 
> Engine name: Xerces
> Severity: error
> Description: Invalid content was found starting with element '{"http://www.tei-c.org/ns/1.0":person}'. One of '{"http://www.tei-c.org/ns/1.0":bibl, "http://www.tei-c.org/ns/1.0":listBibl, "http://www.tei-c.org/ns/1.0":msDesc, "http://www.tei-c.org/ns/1.0":persName, "http://www.tei-c.org/ns/1.0":affiliation, "http://www.tei-c.org/ns/1.0":age, "http://www.tei-c.org/ns/1.0":education, "http://www.tei-c.org/ns/1.0":faith, "http://www.tei-c.org/ns/1.0":floruit, "http://www.tei-c.org/ns/1.0":langKnowledge, "http://www.tei-c.org/ns/1.0":nationality, "http://www.tei-c.org/ns/1.0":occupation, "http://www.tei-c.org/ns/1.0":residence, "http://www.tei-c.org/ns/1.0":sex, "http://www.tei-c.org/ns/1.0":socecStatus, "http://www.tei-c.org/ns/1.0":trait, "http://www.tei-c.org/ns/1.0":birth, "http://www.tei-c.org/ns/1.0":death, "http://www.tei-c.org/ns/1.0":event, "http://www.tei-c.org/ns/1.0":listEvent, "http://www.tei-c.org/ns/1.0":idno, "http://www.tei-c.org/ns/1.0":index, "http://www.tei-c.org/ns/1.0":link, "http://www.tei-c.org/ns/1.0":linkGrp, "http://www.tei-c.org/ns/1.0":span, "http://www.tei-c.org/ns/1.0":spanGrp, "http://www.tei-c.org/ns/1.0":interp, "http://www.tei-c.org/ns/1.0":interpGrp, "http://www.tei-c.org/ns/1.0":substJoin, "http://www.tei-c.org/ns/1.0":listTranspose, "http://www.tei-c.org/ns/1.0":milestone, "http://www.tei-c.org/ns/1.0":gb, "http://www.tei-c.org/ns/1.0":pb, "http://www.tei-c.org/ns/1.0":lb, "http://www.tei-c.org/ns/1.0":cb, "http://www.tei-c.org/ns/1.0":anchor, "http://www.tei-c.org/ns/1.0":fw, "http://www.tei-c.org/ns/1.0":note, "http://www.tei-c.org/ns/1.0":witDetail, "http://www.tei-c.org/ns/1.0":gap, "http://www.tei-c.org/ns/1.0":addSpan, "http://www.tei-c.org/ns/1.0":damageSpan, "http://www.tei-c.org/ns/1.0":delSpan, "http://www.tei-c.org/ns/1.0":space, "http://www.tei-c.org/ns/1.0":notatedMusic, "http://www.tei-c.org/ns/1.0":figure, "http://www.tei-c.org/ns/1.0":metamark}' is expected.
> Start location: 19175:26
> End location: 19175:32
> 
> Engine name: Xerces
> Severity: error
> Description: There are multiple occurrences of ID value 'pertile-giambattista'.
> Start location: 19175:40
> End location: 19175:62
> 
> Engine name: Xerces
> Severity: error
> Description: The value 'pertile-giambattista' of attribute 'xml:id' on element 'person' is not valid with respect to its type, 'ID'.
> Start location: 19175:40
> End location: 19175:62
> 
> Engine name: Xerces
> Severity: fatal
> Description: The element type "forename" must be terminated by the matching end-tag "</forename>".
> Start location: 24029:27
>

**Comment by chaichner** [comment]
sorry, werd drauf achten..


----------
Dr. Christof Aichner

Sekretär der Kommission für Neuere Geschichte Österreichs

Kommission für Neuere Geschichte Österreichs
c/o Institut für Geschichtswissenschaften und europäische Ethnologie
Leopold-Franzens Universität Innsbruck
Innrain 52
6020 Innsbruck

ZVR-Nr. 458463889

http://www.oesterreichische-geschichte.at/

http://thun-korrespondenz.uibk.ac.at

________________________________
Von: Peter Andorfer <notifications@github.com>
Gesendet: Freitag, 13. November 2020 19:17:28
An: KONDE-AT/thun-data
Cc: Aichner, Christof; Assign
Betreff: [KONDE-AT/thun-data] bitte auf Wohlgeformtheit überprüfen (#1)


Bitte nur Dateien committen, die auch wohlgeformt sind
Probleme bei indices/listperson.xml

Bitte nur Dateien committen, die auch wohlgeformt sind
Probleme bei indices/listperson.xml:
Engine name: Xerces
Severity: error
Description: Invalid content was found starting with element '{"http://www.tei-c.org/ns/1.0":person}<http://www.tei-c.org/ns/1.0%22:person%7D>'. One of '{"http://www.tei-c.org/ns/1.0":bibl<http://www.tei-c.org/ns/1.0%22:bibl>, "http://www.tei-c.org/ns/1.0":listBibl<http://www.tei-c.org/ns/1.0%22:listBibl>, "http://www.tei-c.org/ns/1.0":msDesc<http://www.tei-c.org/ns/1.0%22:msDesc>, "http://www.tei-c.org/ns/1.0":persName<http://www.tei-c.org/ns/1.0%22:persName>, "http://www.tei-c.org/ns/1.0":affiliation<http://www.tei-c.org/ns/1.0%22:affiliation>, "http://www.tei-c.org/ns/1.0":age<http://www.tei-c.org/ns/1.0%22:age>, "http://www.tei-c.org/ns/1.0":education<http://www.tei-c.org/ns/1.0%22:education>, "http://www.tei-c.org/ns/1.0":faith<http://www.tei-c.org/ns/1.0%22:faith>, "http://www.tei-c.org/ns/1.0":floruit<http://www.tei-c.org/ns/1.0%22:floruit>, "http://www.tei-c.org/ns/1.0":langKnowledge<http://www.tei-c.org/ns/1.0%22:langKnowledge>, "http://www.tei-c.org/ns/1.0":nationality<http://www.tei-c.org/ns/1.0%22:nationality>, "http://www.tei-c.org/ns/1.0":occupation<http://www.tei-c.org/ns/1.0%22:occupation>, "http://www.tei-c.org/ns/1.0":residence<http://www.tei-c.org/ns/1.0%22:residence>, "http://www.tei-c.org/ns/1.0":sex<http://www.tei-c.org/ns/1.0%22:sex>, "http://www.tei-c.org/ns/1.0":socecStatus<http://www.tei-c.org/ns/1.0%22:socecStatus>, "http://www.tei-c.org/ns/1.0":trait<http://www.tei-c.org/ns/1.0%22:trait>, "http://www.tei-c.org/ns/1.0":birth<http://www.tei-c.org/ns/1.0%22:birth>, "http://www.tei-c.org/ns/1.0":death<http://www.tei-c.org/ns/1.0%22:death>, "http://www.tei-c.org/ns/1.0":event<http://www.tei-c.org/ns/1.0%22:event>, "http://www.tei-c.org/ns/1.0":listEvent<http://www.tei-c.org/ns/1.0%22:listEvent>, "http://www.tei-c.org/ns/1.0":idno<http://www.tei-c.org/ns/1.0%22:idno>, "http://www.tei-c.org/ns/1.0":index<http://www.tei-c.org/ns/1.0%22:index>, "http://www.tei-c.org/ns/1.0":link<http://www.tei-c.org/ns/1.0%22:link>, "http://www.tei-c.org/ns/1.0":linkGrp<http://www.tei-c.org/ns/1.0%22:linkGrp>, "http://www.tei-c.org/ns/1.0":span<http://www.tei-c.org/ns/1.0%22:span>, "http://www.tei-c.org/ns/1.0":spanGrp<http://www.tei-c.org/ns/1.0%22:spanGrp>, "http://www.tei-c.org/ns/1.0":interp<http://www.tei-c.org/ns/1.0%22:interp>, "http://www.tei-c.org/ns/1.0":interpGrp<http://www.tei-c.org/ns/1.0%22:interpGrp>, "http://www.tei-c.org/ns/1.0":substJoin<http://www.tei-c.org/ns/1.0%22:substJoin>, "http://www.tei-c.org/ns/1.0":listTranspose<http://www.tei-c.org/ns/1.0%22:listTranspose>, "http://www.tei-c.org/ns/1.0":milestone<http://www.tei-c.org/ns/1.0%22:milestone>, "http://www.tei-c.org/ns/1.0":gb<http://www.tei-c.org/ns/1.0%22:gb>, "http://www.tei-c.org/ns/1.0":pb<http://www.tei-c.org/ns/1.0%22:pb>, "http://www.tei-c.org/ns/1.0":lb<http://www.tei-c.org/ns/1.0%22:lb>, "http://www.tei-c.org/ns/1.0":cb<http://www.tei-c.org/ns/1.0%22:cb>, "http://www.tei-c.org/ns/1.0":anchor<http://www.tei-c.org/ns/1.0%22:anchor>, "http://www.tei-c.org/ns/1.0":fw<http://www.tei-c.org/ns/1.0%22:fw>, "http://www.tei-c.org/ns/1.0":note<http://www.tei-c.org/ns/1.0%22:note>, "http://www.tei-c.org/ns/1.0":witDetail<http://www.tei-c.org/ns/1.0%22:witDetail>, "http://www.tei-c.org/ns/1.0":gap<http://www.tei-c.org/ns/1.0%22:gap>, "http://www.tei-c.org/ns/1.0":addSpan<http://www.tei-c.org/ns/1.0%22:addSpan>, "http://www.tei-c.org/ns/1.0":damageSpan<http://www.tei-c.org/ns/1.0%22:damageSpan>, "http://www.tei-c.org/ns/1.0":delSpan<http://www.tei-c.org/ns/1.0%22:delSpan>, "http://www.tei-c.org/ns/1.0":space<http://www.tei-c.org/ns/1.0%22:space>, "http://www.tei-c.org/ns/1.0":notatedMusic<http://www.tei-c.org/ns/1.0%22:notatedMusic>, "http://www.tei-c.org/ns/1.0":figure<http://www.tei-c.org/ns/1.0%22:figure>, "http://www.tei-c.org/ns/1.0":metamark}<http://www.tei-c.org/ns/1.0%22:metamark%7D>' is expected.
Start location: 19175:26
End location: 19175:32

Engine name: Xerces
Severity: error
Description: There are multiple occurrences of ID value 'pertile-giambattista'.
Start location: 19175:40
End location: 19175:62

Engine name: Xerces
Severity: error
Description: The value 'pertile-giambattista' of attribute 'xml:id' on element 'person' is not valid with respect to its type, 'ID'.
Start location: 19175:40
End location: 19175:62

Engine name: Xerces
Severity: fatal
Description: The element type "forename" must be terminated by the matching end-tag "".
Start location: 24029:27
