### ISSUE TITLE
keine 'reserved characters' verwenden

### ISSUE THREAD

**Issue by csae8092** [KONDE-AT/thun-data#2]
`&` ist in XML ein spezieller Buchstabe, der 'maskiert' werden muss -> `&amp;`

Das kommt etwa bei URLs vor, z.B. https://books.google.at/books?id=PfVbAAAAcAAJ&dq=Verhandlungen+der+zw%C3%B6lften+Versammlung+deutscher+Philologen,+Schulm%C3%A4nner+und+Orientalisten+in+Erlangen+vom+30.+September+bis+3.+October+1851,+Erlangen+1852.&hl=de&source=gbs_navlinks_s

hier sollte es aber reichen, nur `https://books.google.at/books?id=PfVbAAAAcAAJ` anzugeben

**Comment by chaichner** [comment]
ich hatte da grundsätztlich schon drauf geachtet, jetzt hab ichs vielleicht vergessen.
